// mobile-ionic/src/views/LoginPage.vue
<template>
  <ion-page>
    <ion-content class="auth-page">
      <div class="auth-container">
        <div class="auth-header">
          <h1>🛣️ MADIO</h1>
          <p>Connexion</p>
        </div>

        <form @submit.prevent="handleLogin" class="auth-form">
          <div class="form-group">
            <label>Email</label>
            <ion-input 
              v-model="email" 
              type="email" 
              placeholder="votre@email.com"
              class="form-input"
              required
            ></ion-input>
          </div>

          <div class="form-group">
            <label>Mot de passe</label>
            <ion-input 
              v-model="password" 
              type="password" 
              placeholder="••••••••"
              class="form-input"
              required
            ></ion-input>
          </div>

          <div v-if="error" class="error-message">{{ error }}</div>

          <ion-button expand="block" type="submit" :disabled="loading" class="btn-submit">
            <ion-spinner v-if="loading" name="crescent"></ion-spinner>
            <span v-else>🔐 Se connecter</span>
          </ion-button>

          <div class="auth-footer">
            <a @click="goToRegister" class="auth-link">Créer un compte</a>
          </div>
        </form>
      </div>
    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { IonPage, IonContent, IonInput, IonButton, IonSpinner, toastController } from '@ionic/vue'
import { useAuthStore } from '@/stores/auth'

const router = useRouter()
const authStore = useAuthStore()
const email = ref('')
const password = ref('')
const loading = ref(false)
const error = ref<string | null>(null)

function goToRegister() {
  router.push('/register')
}

async function handleLogin() {
  error.value = null
  loading.value = true
  try {
    await authStore.login(email.value, password.value)
    router.push('/map')
  } catch (err: any) {
    error.value = err.response?.data?.message || 'Email ou mot de passe incorrect'
    const toast = await toastController.create({ message: error.value || 'Erreur de connexion', duration: 3000, color: 'danger' })
    toast.present()
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.auth-page {
  --background: linear-gradient(135deg, #2c3e50 0%, #3498db 100%);
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
}

.auth-container {
  background: white;
  border-radius: 20px;
  padding: 40px 30px;
  width: 90%;
  max-width: 400px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
  margin: 20px;
}

.auth-header {
  text-align: center;
  margin-bottom: 35px;
}

.auth-header h1 {
  font-size: 2.2rem;
  margin: 0;
  color: #2c3e50;
}

.auth-header p {
  font-size: 1.1rem;
  color: #7f8c8d;
  margin: 8px 0 0;
}

.auth-form {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.form-group label {
  font-weight: 600;
  color: #2c3e50;
  font-size: 0.95rem;
}

.form-input {
  --padding-start: 16px;
  --padding-end: 16px;
  --padding-top: 14px;
  --padding-bottom: 14px;
  --background: #ffffff;
  --color: #2c3e50;
  --placeholder-color: #bdc3c7;
  border: 2px solid #e0e0e0;
  border-radius: 10px;
  font-size: 1rem;
  transition: all 0.2s;
}

.form-input:focus-within {
  border-color: #3498db;
  box-shadow: 0 0 0 4px rgba(52, 152, 219, 0.15);
}

.error-message {
  background: #fdedee;
  border: 1px solid #e74c3c;
  color: #c0392b;
  padding: 14px;
  border-radius: 10px;
  text-align: center;
  font-size: 0.95rem;
}

.btn-submit {
  --background: linear-gradient(135deg, #3498db, #2980b9);
  --border-radius: 12px;
  font-weight: 600;
  height: 50px;
  margin-top: 10px;
}

.btn-submit:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(52, 152, 219, 0.4);
}

.auth-footer {
  display: flex;
  justify-content: space-between;
  padding-top: 15px;
  border-top: 1px solid #ecf0f1;
  margin-top: 10px;
}

.auth-link {
  color: #3498db;
  text-decoration: none;
  font-size: 0.95rem;
  font-weight: 500;
  cursor: pointer;
  transition: color 0.2s;
}

.auth-link:hover {
  color: #2980b9;
  text-decoration: underline;
}
</style>

// frontend/src/pages/LoginPage.tsx
import { useState, useEffect, type FormEvent } from 'react'
import { Link, useNavigate, useLocation } from 'react-router-dom'

const styles = `
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%);
    min-height: 100vh;
  }

  .auth-page {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 20px;
    background: linear-gradient(135deg, #1a3a52 0%, #2c5282 100%);
  }

  .auth-container {
    width: 100%;
    max-width: 420px;
    background: white;
    border-radius: 12px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
    overflow: hidden;
    animation: slideUp 0.6s ease-out;
  }

  @keyframes slideUp {
    from {
      opacity: 0;
      transform: translateY(40px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  .auth-header {
    background: linear-gradient(135deg, #2c5282 0%, #1a3a52 100%);
    color: white;
    padding: 40px 30px;
    text-align: center;
    border-bottom: 5px solid #f5a623;
  }

  .auth-header h1 {
    font-size: 2.5em;
    font-weight: 700;
    letter-spacing: 2px;
    margin-bottom: 10px;
  }

  .auth-header p {
    font-size: 0.95em;
    opacity: 0.9;
    font-weight: 300;
  }

  .auth-form {
    padding: 40px 30px;
  }

  .form-group {
    margin-bottom: 25px;
  }

  .form-group label {
    display: block;
    margin-bottom: 8px;
    font-weight: 600;
    color: #2c5282;
    font-size: 0.95em;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .form-group input {
    width: 100%;
    padding: 12px 15px;
    border: 2px solid #e0e0e0;
    border-radius: 8px;
    font-size: 1em;
    transition: all 0.3s ease;
    background-color: #f9f9f9;
  }

  .form-group input:focus {
    outline: none;
    border-color: #2c5282;
    background-color: white;
    box-shadow: 0 0 0 3px rgba(44, 82, 130, 0.1);
  }

  .form-group input::placeholder {
    color: #999;
  }

  .success-message {
    background: linear-gradient(135deg, #27ae60 0%, #229954 100%);
    color: white;
    padding: 15px 15px;
    border-radius: 8px;
    margin-bottom: 25px;
    font-size: 0.95em;
    border-left: 4px solid #f5a623;
  }

  .success-message p {
    margin-top: 8px;
    font-size: 0.85em;
    opacity: 0.95;
  }

  .error-message {
    background: linear-gradient(135deg, #e74c3c 0%, #c0392b 100%);
    color: white;
    padding: 15px 15px;
    border-radius: 8px;
    margin-bottom: 25px;
    font-size: 0.95em;
    border-left: 4px solid #f5a623;
    animation: shake 0.5s ease-in-out;
  }

  @keyframes shake {
    0%, 100% { transform: translateX(0); }
    25% { transform: translateX(-10px); }
    75% { transform: translateX(10px); }
  }

  .btn-submit {
    width: 100%;
    padding: 14px;
    background: linear-gradient(135deg, #2c5282 0%, #1a3a52 100%);
    color: white;
    border: none;
    border-radius: 8px;
    font-size: 1em;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.3s ease;
    text-transform: uppercase;
    letter-spacing: 1px;
    margin-bottom: 20px;
    box-shadow: 0 4px 15px rgba(44, 82, 130, 0.3);
  }

  .btn-submit:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: 0 6px 20px rgba(44, 82, 130, 0.4);
  }

  .btn-submit:active:not(:disabled) {
    transform: translateY(0);
  }

  .btn-submit:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .auth-footer {
    display: flex;
    gap: 15px;
    justify-content: center;
    padding-top: 20px;
    border-top: 1px solid #e0e0e0;
  }

  .auth-footer a {
    color: #2c5282;
    text-decoration: none;
    font-weight: 600;
    font-size: 0.9em;
    transition: all 0.3s ease;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .auth-footer a:hover {
    color: #f5a623;
  }
`

export default function LoginPage() {
  const navigate = useNavigate()
  const location = useLocation()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [successMessage, setSuccessMessage] = useState<string | null>(null)

  useEffect(() => {
    const state = location.state as { message?: string; firebaseSynced?: boolean } | null
    if (state?.message) {
      setSuccessMessage(state.message)
      window.history.replaceState({}, document.title)
    }
  }, [location])

  async function onSubmit(e: FormEvent) {
    e.preventDefault()
    setError(null)
    setSuccessMessage(null)
    setLoading(true)

    try {
      const response = await fetch('http://localhost:8080/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password }),
      })

      const data = await response.json()

      if (response.ok && (data.success || data.token || data.userId || data.id)) {
        const userData = data.user || data
        localStorage.setItem('user', JSON.stringify({
          userId: userData.userId || userData.id,
          email: userData.email || email,
          nom: userData.nom,
          prenom: userData.prenom,
          role: userData.role || 'USER',
          token: data.token,
        }))
        navigate('/', { replace: true })
      } else {
        setError(data.message || 'Email ou mot de passe incorrect')
      }
    } catch (err) {
      setError('Erreur de connexion au serveur')
    } finally {
      setLoading(false)
    }
  }

  return (
    <>
      <style>{styles}</style>
      <div className="auth-page">
        <div className="auth-container">
          <div className="auth-header">
            <h1>MADIO</h1>
            <p>Connexion Sécurisée</p>
          </div>

          <form onSubmit={onSubmit} className="auth-form">
            {successMessage && (
              <div className="success-message">
                {successMessage}
                <p>Vous pouvez maintenant vous connecter sur l'application mobile.</p>
              </div>
            )}

            <div className="form-group">
              <label>Adresse E-mail</label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="votre@email.com"
                required
              />
            </div>

            <div className="form-group">
              <label>Mot de passe</label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="••••••••"
                required
              />
            </div>

            {error && <div className="error-message">{error}</div>}

            <button type="submit" className="btn-submit" disabled={loading}>
              {loading ? 'Connexion en cours...' : 'Se connecter'}
            </button>

            <div className="auth-footer">
              <Link to="/">Retour à l'accueil</Link>
              <Link to="/register">Créer un compte</Link>
            </div>
          </form>
        </div>
      </div>
    </>
  )
}
